<a href="https://colab.research.google.com/github/Yamile222768/Clases/blob/main/NumPY_clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #definimos el alias de numpy

a = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.shape

(3, 4)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a[0, 3:5]

array([4])

In [ ]:
b=a
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b[1,2]=2024
b

array([[   1,    2,    3,    4],
       [   5,    6, 2024,    8],
       [   9,   10,   11,   12]])

In [ ]:
a #shallow copy cualquier cosa que modifique en b se modifica en a pq hicimos b=a

array([[   1,    2,    3,    4],
       [   5,    6, 2024,    8],
       [   9,   10,   11,   12]])

In [ ]:
c = np.copy(a) #copy para utilizar los datos pero sin modificas los datos del que lo estamos copiando
c

array([[   1,    2,    3,    4],
       [   5,    6, 2024,    8],
       [   9,   10,   11,   12]])

In [ ]:
b

array([[   1,    2,    3,    4],
       [   5,    6, 2024,    8],
       [   9,   10,   11,   12]])

In [ ]:
a

array([[   1,    2,    3,    4],
       [   5,    6, 2024,    8],
       [   9,   10,   11,   12]])